# Generated by Django 3.2.4 on 2021-06-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao_da_conta', models.CharField(max_length=30)),
                ('valor_da_conta', models.DecimalField(decimal_places=2, max_digits=999999999)),
            ],
        ),
    ]
